title: sandpaper ltd.
description: tangens rnd division development board
author: "undisclosed"

theme: minima

base_url: /sandpaperltd.github.io/
repository: /sandpaperltd/sandpaperltd.github.io

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  
header_pages:
  - _pages/frontpage.md

include:
    - _pages

